name: HACS Action

on:
  push:
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
