name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master
